# Generated by Django 3.1.6 on 2021-08-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('date', models.DateField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
